import { std } from "wow/wotlk";
import { createAbility } from "../../functions/createAbility";

// Create 25% Mana Restore //
const MANA_RESTORE = std.Spells.create("azara-core", "mana-regen")
    .Name.enGB.set("Mana Restore")
    .Range.set(1)
    .Visual.set(7265)
    .Visual.modRefCopy(visual => {
        visual.PrecastKit.set(3790)
    })
    .Effects.addMod(eff => eff
        .Type.ENERGIZE_PCT.set()
        .PowerType.MANA.set()
        .PowerPctBase.set(2.5)
        .ImplicitTargetA.UNIT_CASTER.set()
    )
       // .Attributes.IS_HIDDEN_FROM_LOG.set(true)

// Create Spell //
const SPELL = std.Spells.create("azara-core", "arcane-bolt-ability")
export const ARCANE_BOLT = createAbility(SPELL.ID)
SPELL.Name.enGB.set("Arcane Bolt")
    .Description.enGB.set("Sends a magical bolt at the enemy, causing $s1 Arcane damage.")
    .Icon.setPath("Spell_Arcane_Starfire")
    .PreventionType.SILENCE.set()
    .FacingCasterFlags.set("SPELL_FACING_FLAG_INFRONT")
    .Attributes.set(['NOT_SHAPESHIFTED'])
    .InterruptFlags.set(['ON_MOVEMENT','ON_PUSHBACK','ON_INTERRUPT_CAST','ON_INTERRUPT'])
    .SchoolMask.set(['PHYSICAL','SHADOW'])
    .Visual.set(271)
    .DefenseType.set(1)
    .Speed.set(20)
    .CastTime.setSimple(1700)
    .Cooldown.GlobalTime.set(1500)
    .Cooldown.GlobalCategory.set(133)
    .Power.Type.MANA.set()
    .Power.CostPercent.set(10)
    .Range.setSimple(0, 30)
    .Effects.addMod(x => x
        .Type.SCHOOL_DAMAGE.set()
        .DamageBase.set(12)
        .DamageDieSides.set(5)
        .DamagePerLevel.set(0.4000000059604645)
        .BonusMultiplier.set(0.14000000059604645)
        .ImplicitTargetA.UNIT_TARGET_ENEMY.set()
    )
    .Effects.addMod(x => x
        .Type.APPLY_AURA.set()
        .Aura.PROC_TRIGGER_SPELL.set()
        .TriggeredSpell.set(MANA_RESTORE.ID)
        .ImplicitTargetA.UNIT_CASTER.set()
    )
    .Proc.HitMask.CRITICAL.set(true)
    .Proc.Chance.set(100)
    .Proc.TypeMask.DAMAGE.set(true)
    .Proc.PhaseMask.HIT.set(true)
    .Proc.TriggerMask.DONE_SPELL_MAGIC_DAMAGE_CLASS_POSITIVE.set(true)